---
title: "Tidy_Tuesday_2020_06_23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Tidy Tuesday: Slavery in the US

https://www.nationalgeographic.com/culture/2019/08/how-slavery-flourished-united-states-chart-maps/#close


## Load libraries

```{r load_libraries, warning=FALSE, message=FALSE}
library(tidyverse)
library(scales)
library(ggtext)
library(hrbrthemes)
library(paletteer)
library(trelliscopejs)
```

## Get Data

```{r get_data, warning=FALSE, message=FALSE}
census <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/census.csv')
slave_routes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-06-16/slave_routes.csv')

```

## Data Wrangling 

```{r data_wrangling, message=FALSE}
slave_routes_df<- slave_routes %>%
  mutate(port_origin= str_remove(port_origin, ", port unspecified")) %>%
  mutate(port_arrival= str_remove(port_arrival, ", port unspecified"))  %>%
  filter(!is.na(port_arrival)) %>%
  filter(!is.na(n_slaves_arrived)) %>%
  filter(!is.na(year_arrival)) %>%
  mutate_if(is.character, list(~replace_na(., "unknown")))


census_df<- census %>%
  select(-black) %>%
  mutate_at(c("white", "black_free", "black_slaves"), funs(100* . / total)) %>%
  mutate_at(c("white", "black_free", "black_slaves"), funs(round(.,2))) %>%
  group_by(region, year) %>%
  arrange((desc(total))) %>%
  top_n(1, total) %>%
  select(-total) %>%
  select(-division) %>%
  distinct %>%
  ungroup %>%
  pivot_longer(white:black_slaves, names_to = "group", values_to = "perc")  %>%
  mutate(year = factor(year), 
         year = factor(year, levels = rev(levels(year))))

check_palettes<- palettes_d_names
```

## Visualizations


```{r fig.width= 10, fig.height=8, warning=FALSE, message=FALSE}

ggplot(census_df %>% ungroup %>% filter(!region %in% c("USA Total", "West")) %>% filter(!group=="black")) +
  geom_col(aes(year, perc, fill= group), position = "stack") +
  facet_grid(.~region) +
  coord_flip() +
  hrbrthemes::theme_ipsum(axis = FALSE,
                          axis_title_just = "l",
                          grid = FALSE) +
  paletteer::scale_fill_paletteer_d(palette = "ggthemes::wsj_dem_rep") +
  labs(title = "Census data from 1790 to 1870", 
       subtitle = "Proportions of <span style='color:#A8A6A7;'>**whites**</span>, <span style='color:#B12839;'>**slaves**</span> or <span style='color:#00698E;'>**free black**</span> people") +
  theme(axis.title = element_text(color = "white"), 
        axis.text.x = element_blank(),
        plot.subtitle = element_markdown(),
        plot.title.position = "plot",
        legend.position = "none",
        strip.text = element_textbox(face = "bold"))



```


## Interactive visualization

```{r inter, eval=FALSE}

qplot(year_arrival, n_slaves_arrived, data = slave_routes_df) +
  theme_bw() +
  facet_trelliscope(~ port_arrival, nrow = 2, ncol = 7, width = 300)

```
