---
title: "TidyTuesday"
output: github_document
always_allow_html: true
---

# Who are we?
Some [Pinto lab](https://www.pintolab.com/) members, under [Chris Anderson](https://github.com/chrisLanderson) lead, meet every Tuesday to discuss visualization and analyses of [TidyTuesday](https://github.com/rfordatascience/tidytuesday) data.  

# Objectives
As a group exercise the objectives are:  

* gain proficiency with R:  
    + learn about new packages
    + improve code readability
    + improve visualization techniques  
* learn from each other  
* do (some) research outside our own and have fun!

In this repo I will be documenting *my* contribution. In most folders, there will be an md file. If you'd like to have a human readable document click on this file, else you can download the Rmarkdown also within the folders and run the commands in your local computer.  


# Disclaimer
Time spent on TidyTuesdays is limited to 3-5 hrs a week. The analyses/visualizations might not be the most sophisticated, but a lot of learning is happening! :)  

Please exercise caution and your own judgment if using any of the info herein. Also note, that some of the renderings are not faithfully reproduced when exported to a markdown file.


# Completed
So far I have looked at data about:

1. Australian fires  
2. Passwords  
3. Spotify  
4. San Francisco trees  
5. NFL attendance  
6. Hotels  
7. ~~Food's carbon print~~  
8. Measles  
9. NHL  
10. College tuition  
11. The Office  
12. Brain injuries  
13. Beer  
14. Tour de France
15. Rap artists
16. GDPR fines
17. Broadway
18. Animal Crossing
19. Volcanos
20. Volleyball  
21. Cocktails  
22. ~~Marbles~~  
23. African-american achievement  
24. Slavery  
25. ~~Caribou~~  
26. X-men  
27. Coffee  
28. Astronauts  
29. ~~Australian animals~~ / Internal: Reproducible research  
30. Palmer Penguins  
31. European Energy
32. ~~Avatar: The Last Airbender~~ /Internal: Hierarchical data

27 out of 32, what a streak!

```{r eval=TRUE, echo=FALSE}
library(flexdashboard)
gauge(27, min = 0, max = 48, gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
), label = 'Projects')
```
