---
title: "TidyTuesday_2020_07_21"
output: github_document
---
# Tidy Tuesday: Astronauts

`dataMaid` package produces similar output to `skimr`, but generates a pdf report.  https://github.com/ekstroem/dataMaid
`visdat` https://docs.ropensci.org/visdat/
`janitor` https://github.com/sfirke/janitor
  
## Load libraries
  
```{r load_libraries, warning=FALSE, message=FALSE}
suppressPackageStartupMessages(library(tidyverse))
library(skimr)
library(dataMaid)
library(hrbrthemes)
library(paletteer)
library(ggtext)

library(visdat)
```

## Get Data

```{r get_data, warning=FALSE, message=FALSE}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')

```

## Inspect Data

```{r inspect_data, warning=FALSE, message=FALSE}
skim(astronauts)

#makeDataReport(astronauts)

#cumulative hours by single astronaut
astronauts %>%
  group_by(name, nationality) %>%
  summarise(max_hrs= max(total_hrs_sum)) %>%
  arrange(desc(max_hrs))

#number of astronauts per nationality
astronauts %>%
  select(name, nationality) %>%
  distinct() %>%
  group_by(nationality) %>%
  summarise(astronauts= n()) %>%
  arrange(desc(astronauts))


astronauts %>%
  select(name, nationality, occupation, military_civilian) %>%
  distinct() %>%
  group_by(nationality, occupation, military_civilian) %>%
  summarise(astronauts= n()) %>%
  arrange(desc(astronauts))

# number of missions: total_number_of_missions
# age: year_of_birth
# age first mission: year_of_selection
# occupation
# military_civilian
# nationality
# sex
```

## Data Wrangling 

```{r data_wrangling, message=FALSE}

astronauts_df<- astronauts %>%
  mutate(occupation= ifelse(occupation %in% c("flight engineer", "Flight engineer"), "flight_engineer", occupation)) %>%
  mutate(occupation= ifelse(occupation %in% c("Other (space tourist)", "Other (Space tourist)", "Space tourist"), "tourist", occupation)) %>%
  mutate(occupation= ifelse(occupation %in% c("pilot", "Pilot"), "pilot", occupation)) %>%
  mutate(occupation= ifelse(occupation == "MSP", "mission_specialist", occupation)) %>%
  mutate(occupation= ifelse(occupation == "PSP", "payload_specialist", occupation)) %>%
  mutate(occupation= ifelse(occupation == "Other (Journalist)", "journalist", occupation)) %>%
  mutate(occupation= ifelse(occupation == "spaceflight participant", "participant", occupation))

vis_dat(astronauts_df)
vis_miss(astronauts_df)
vis_cor(astronauts_df %>%
          select(which(sapply(.,class)=="numeric")))

astronaut_df_hrs<- astronauts_df %>%
  select(name, year_of_mission, total_hrs_sum) %>%
  distinct() %>%
  mutate(decade = floor(year_of_mission/10)*10) %>%
  mutate(decade=as.character(decade))

#occupation as astronaut --> fix 
levels(as.factor(astronauts$occupation))
janitor::make_clean_names(levels(as.factor(astronauts$occupation)))

astronaut_df_occupation<- astronauts_df %>%
  select(name, year_of_mission, occupation) %>%
  distinct() %>%
  mutate(decade = floor(year_of_mission/10)*10) %>%
  group_by(decade, occupation) %>%
  summarise(counts= n()) %>%
  ungroup() %>%
  group_by(decade) %>%
  mutate(total= sum(counts)) %>%
  mutate(proportion= 100*counts/total) %>%
  mutate(decade=as.character(decade))

astronaut_df_sex<- astronauts_df %>%
  select(name, year_of_mission, sex) %>%
  distinct() %>%
  mutate(decade = floor(year_of_mission/10)*10) %>%
  group_by(decade, sex) %>%
  summarise(counts= n()) %>%
  ungroup() %>%
  group_by(decade) %>%
  mutate(total= sum(counts)) %>%
  mutate(proportion= 100*counts/total) %>%
  mutate(decade=as.character(decade))

```

## Visualizations


```{r fig.width= 10, fig.height=8, warning=FALSE, message=FALSE}
ggplot(astronaut_df_hrs) +
  geom_boxplot(aes(decade, total_hrs_sum, fill=decade)) +
  scale_fill_paletteer_d("ggsci::lanonc_lancet") +
  labs(title = "Increase in total mission duration hours over the years") +
  hrbrthemes::theme_ipsum_tw() +
  theme(axis.title = element_blank(), 
        plot.title = element_markdown(),
        plot.title.position = "plot")

ggplot(astronaut_df_occupation) +
  geom_bar(aes(decade, proportion, fill= occupation), stat = "identity") +
  scale_fill_paletteer_d("ggsci::lanonc_lancet") +
  labs(title = "Change in propotion of occupations per decade")   +
  hrbrthemes::theme_ipsum_tw() +
  theme(axis.title = element_blank(), 
        plot.title = element_markdown(),
        plot.title.position = "plot")

ggplot(astronaut_df_sex) +
  geom_bar(aes(decade, proportion, fill= sex), stat = "identity") +
  scale_fill_paletteer_d("ggsci::lanonc_lancet") +
  labs(title = "Slow increase of female participation")   +
  hrbrthemes::theme_ipsum_tw() +
  theme(axis.title = element_blank(), 
        plot.title = element_markdown(),
        plot.title.position = "plot")
```
